"""Token Blacklist

Revision ID: 1e25f503b837
Revises: 762ce372fd48
Create Date: 2026-05-15 19:45:55.430078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e25f503b837'
down_revision: Union[str, Sequence[str], None] = '762ce372fd48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('pending', 'building', 'deployed', 'failed', name='project_status'),
               type_=sa.Enum('pending', 'building', 'deployed', 'failed', name='project_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('pending', 'building', 'deployed', 'failed', name='project_status'),
               type_=postgresql.ENUM('pending', 'building', 'deployed', 'failed', name='project_status'),
               existing_nullable=False)
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###
