"""fix_vm_request_status_enum

Revision ID: 2f2ee5d595c4
Revises: 1e25f503b837
Create Date: 2026-05-24 21:29:06.502921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f2ee5d595c4'
down_revision: Union[str, Sequence[str], None] = '1e25f503b837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('pending', 'building', 'deployed', 'failed', name='project_status'),
               type_=sa.Enum('pending', 'building', 'deployed', 'failed', name='project_status'),
               existing_nullable=False)
    op.alter_column('vm_requests', 'os',
               existing_type=postgresql.ENUM('ubuntu_22', 'ubuntu_24', 'debian_12', name='vmoperatingsystem'),
               type_=sa.Enum('ubuntu_22', 'ubuntu_24', 'debian_12', name='vmoperatingsystem', native_enum=False),
               existing_nullable=False)
    op.alter_column('vm_requests', 'status',
               existing_type=postgresql.ENUM('pending', 'rejected', 'running', 'stopped', 'destroyed', name='vmrequeststatus'),
               type_=sa.Enum('pending', 'approved', 'rejected', 'ready', 'running', 'stopped', 'destroyed', name='vmrequeststatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vm_requests', 'status',
               existing_type=sa.Enum('pending', 'approved', 'rejected', 'ready', 'running', 'stopped', 'destroyed', name='vmrequeststatus', native_enum=False),
               type_=postgresql.ENUM('pending', 'rejected', 'running', 'stopped', 'destroyed', name='vmrequeststatus'),
               existing_nullable=False)
    op.alter_column('vm_requests', 'os',
               existing_type=sa.Enum('ubuntu_22', 'ubuntu_24', 'debian_12', name='vmoperatingsystem', native_enum=False),
               type_=postgresql.ENUM('ubuntu_22', 'ubuntu_24', 'debian_12', name='vmoperatingsystem'),
               existing_nullable=False)
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('pending', 'building', 'deployed', 'failed', name='project_status'),
               type_=postgresql.ENUM('pending', 'building', 'deployed', 'failed', name='project_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
