"""Modified projects enum

Revision ID: 4bc7c5c103f2
Revises: 2c0da9a1654a
Create Date: 2026-04-12 16:53:43.132309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bc7c5c103f2'
down_revision: Union[str, Sequence[str], None] = '2c0da9a1654a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('pending', 'building', 'deployed', 'failed', name='project_status'),
               type_=sa.Enum('pending', 'building', 'deployed', 'failed', name='project_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('pending', 'building', 'deployed', 'failed', name='projectstatus'),
               type_=postgresql.ENUM('pending', 'building', 'deployed', 'failed', name='project_status'),
               existing_nullable=False)
    # ### end Alembic commands ###
