"""Models creation

Revision ID: 762ce372fd48
Revises: 73c3efc8dbca
Create Date: 2026-05-15 18:12:33.381790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '762ce372fd48'
down_revision: Union[str, Sequence[str], None] = '73c3efc8dbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('pending', 'building', 'deployed', 'failed', name='project_status'),
               type_=sa.Enum('pending', 'building', 'deployed', 'failed', name='project_status'),
               existing_nullable=False)
    op.create_index(op.f('ix_vm_requests_id'), 'vm_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vm_requests_id'), table_name='vm_requests')
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('pending', 'building', 'deployed', 'failed', name='projectstatus'),
               type_=postgresql.ENUM('pending', 'building', 'deployed', 'failed', name='project_status'),
               existing_nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###
