"""Setuping Models

Revision ID: d20cc3e6b3e8
Revises: 4bc7c5c103f2
Create Date: 2026-04-12 21:38:33.885349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd20cc3e6b3e8'
down_revision: Union[str, Sequence[str], None] = '4bc7c5c103f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'manager', 'developer', 'viewer', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'banned', name='userstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('pipelines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by_id', sa.UUID(), nullable=True),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('commit_message', sa.String(length=255), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('triggered', 'running', 'success', 'failed', 'canceled', name='pipelinestatus'), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['triggered_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    op.create_index(op.f('ix_pipelines_project_id'), 'pipelines', ['project_id'], unique=False)
    op.create_table('project_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_index(op.f('ix_project_members_project_id'), 'project_members', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_members_user_id'), 'project_members', ['user_id'], unique=False)
    op.create_table('vm_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('cpu_cores', sa.Integer(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('disk_gb', sa.Integer(), nullable=False),
    sa.Column('os', sa.Enum('ubuntu_22', 'ubuntu_24', 'debian_12', name='vmoperatingsystem'), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('duration_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'rejected', 'running', 'stopped', 'destroyed', name='vmrequeststatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('vm_id', sa.String(length=100), nullable=True),
    sa.Column('vm_ip_address', sa.String(length=45), nullable=True),
    sa.Column('vm_ssh_user', sa.String(length=50), nullable=True),
    sa.Column('vm_ssh_port', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vm_requests_project_id'), 'vm_requests', ['project_id'], unique=False)
    op.create_index(op.f('ix_vm_requests_requester_id'), 'vm_requests', ['requester_id'], unique=False)
    op.create_table('deployments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('image_tag', sa.String(length=255), nullable=False),
    sa.Column('commit_sha', sa.String(length=40), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('deployment_url', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'deploying', 'running', 'degraded', 'failed', 'rolled_back', name='deploymentstatus'), nullable=False),
    sa.Column('replicas_desired', sa.Integer(), nullable=False),
    sa.Column('replicas_ready', sa.Integer(), nullable=False),
    sa.Column('previous_image_tag', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('deployed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id')
    )
    op.create_index(op.f('ix_deployments_id'), 'deployments', ['id'], unique=False)
    op.create_index(op.f('ix_deployments_project_id'), 'deployments', ['project_id'], unique=False)
    op.create_table('pipeline_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('source_checkout', 'code_analysis', 'unit_tests', 'build', 'security_scan', 'push_registry', 'deploy', name='stagetype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', 'skipped', name='stagestatus'), nullable=False),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_stages_id'), 'pipeline_stages', ['id'], unique=False)
    op.create_index(op.f('ix_pipeline_stages_pipeline_id'), 'pipeline_stages', ['pipeline_id'], unique=False)
    op.create_table('security_scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('image_tag', sa.String(length=255), nullable=False),
    sa.Column('scan_tool', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'passed', 'failed', name='scanstatus'), nullable=False),
    sa.Column('critical_count', sa.Integer(), nullable=False),
    sa.Column('high_count', sa.Integer(), nullable=False),
    sa.Column('medium_count', sa.Integer(), nullable=False),
    sa.Column('low_count', sa.Integer(), nullable=False),
    sa.Column('vulnerabilities', sa.JSON(), nullable=True),
    sa.Column('is_blocking', sa.Boolean(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_scans_id'), 'security_scans', ['id'], unique=False)
    op.create_index(op.f('ix_security_scans_pipeline_id'), 'security_scans', ['pipeline_id'], unique=True)
    op.add_column('projects', sa.Column('branch', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('last_commit_sha', sa.String(length=40), nullable=True))
    op.add_column('projects', sa.Column('deployment_url', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('projects', 'status',
               existing_type=postgresql.ENUM('pending', 'building', 'deployed', 'failed', name='project_status'),
               type_=sa.Enum('pending', 'building', 'deployed', 'failed', name='project_status'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('pending', 'building', 'deployed', 'failed', name='project_status'),
               type_=postgresql.ENUM('pending', 'building', 'deployed', 'failed', name='project_status'),
               existing_nullable=False)
    op.drop_column('projects', 'deleted_at')
    op.drop_column('projects', 'is_deleted')
    op.drop_column('projects', 'deployment_url')
    op.drop_column('projects', 'last_commit_sha')
    op.drop_column('projects', 'branch')
    op.drop_index(op.f('ix_security_scans_pipeline_id'), table_name='security_scans')
    op.drop_index(op.f('ix_security_scans_id'), table_name='security_scans')
    op.drop_table('security_scans')
    op.drop_index(op.f('ix_pipeline_stages_pipeline_id'), table_name='pipeline_stages')
    op.drop_index(op.f('ix_pipeline_stages_id'), table_name='pipeline_stages')
    op.drop_table('pipeline_stages')
    op.drop_index(op.f('ix_deployments_project_id'), table_name='deployments')
    op.drop_index(op.f('ix_deployments_id'), table_name='deployments')
    op.drop_table('deployments')
    op.drop_index(op.f('ix_vm_requests_requester_id'), table_name='vm_requests')
    op.drop_index(op.f('ix_vm_requests_project_id'), table_name='vm_requests')
    op.drop_table('vm_requests')
    op.drop_index(op.f('ix_project_members_user_id'), table_name='project_members')
    op.drop_index(op.f('ix_project_members_project_id'), table_name='project_members')
    op.drop_table('project_members')
    op.drop_index(op.f('ix_pipelines_project_id'), table_name='pipelines')
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    op.drop_table('pipelines')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
